[workspace]
members = [
    "crates/core",
    "crates/cli",
    "crates/gui",
]
resolver = "2"

[workspace.dependencies]
uuid = { version = "1.1.2", features = ["v4"] }
thunderstorm-core = { path = "crates/core" }
